### ISSUE TITLE
فصل دو

### ISSUE THREAD

**Issue by Farzadnaghavi** [ftg-iran/aip-persian#10]
میخوام فصل دو رو ترجمه کنم

**Comment by mthri** [comment]
میتونید شروع کنید
زمان پایان ترجمه رو هم اعلام کنید لطفا

**Comment by Farzadnaghavi** [comment]
حداکثر دو هفته

**Comment by mmdbalkhi** [comment]
@Farzadnaghavi سلام. بیشتر از دو هفته از زمان اعلامی شما برای ترجمه گذشته‌ آیا برنامه ای برای ترجمه ندارین؟
