### ISSUE TITLE
فصل 4

### ISSUE THREAD

**Issue by FatemeFouladkar** [ftg-iran/aip-persian#13]
سلام. میخوام فصل 4 رو ترجمه کنم 
تاریخ پایان: اول فروردین

**Comment by mmdbalkhi** [comment]
سلام @FatemeFouladkar چند روزه که از موعود گذشته آیا برنامه ای برای ترجمه ندارید؟

**Comment by FatemeFouladkar** [comment]
سلام. @mmdbalkhi  سه روز پیش pr دادم و مرج شد 
https://github.com/ftg-iran/aip-persian/pull/19

**Comment by mmdbalkhi** [comment]
سلام ممنون از مشارکتون.
