### ISSUE TITLE
مقدمه کتاب

### ISSUE THREAD

**Issue by MKarimi21** [ftg-iran/aip-persian#21]
با سلام
اگر [@mahdiashtian](https://github.com/mahdiashtian) فرصت ترجمه مقدمه را نداشته باشد میخواهم بخش اول مقدمه را شروع به ترجمه کنم

**Comment by mmdbalkhi** [comment]
> با سلام اگر [@mahdiashtian](https://github.com/mahdiashtian) فرصت ترجمه مقدمه را نداشته باشد میخواهم بخش اول مقدمه را شروع به ترجمه کنم

سلام. اگه ایشون تا جمعه(۱۱ فروردین) پیامی نفرستادن لطفا شروع کنید.
