### ISSUE TITLE
فصل سوم - 1-684

### ISSUE THREAD

**Issue by p-ndr** [ftg-iran/aip-persian#22]
Hello, I would like to request any of the three chapters posted for translation. I could translate all, or even one of them.

**Comment by mmdbalkhi** [comment]
سلام. لطفاً تا [خط ۶۸۴ فصل سوم](https://github.com/ftg-iran/aip-persian/blob/36af584c9c81fbba534d317d8d696230ac57d29a/03-Asyncio%20Walk-Through/README.md?plain=1#L684) ترجمه کنید.

همچنین لطفاً زمان حدودی اتمام ترجمه رو هم اعلام کنید.

**Comment by p-ndr** [comment]
حدودا تا هشت اردیبهشت تمومش می کنم.
به روز رسانی: من متاسفانه یه مشکلی برام پیش اومده، تایم تحویلم حوالی ۱۵ اردیبهشت می‌شه،

**Comment by mmdbalkhi** [comment]
@p-ndr سلام. منتظر هستیم.

**Comment by p-ndr** [comment]
شرمنده‌م این قدر طول کشیده، چندین چیز با هم اتفاق افتاده بود این مدت، چیزی ازش نمونده، کمتر از یک‌سومش باقی مونده

**Comment by mmdbalkhi** [comment]
سلام مشکلی نیست. هروقت تموم شد PR ایجاد کنید.
