### ISSUE TITLE
 ترجمه بخش یک asynchronous in python

### ISSUE THREAD

**Issue by Rahimz** [ftg-iran/aip-persian#23]
درخواست ترجمه بخش یک کتاب asynchronous in python را دارم.

**Comment by mmdbalkhi** [comment]
سلام. لطفاً حدود پایان کارو هم اعلام کنید.

**Comment by Rahimz** [comment]
تا جمعه ۱ اردیبهشت

**Comment by Rahimz** [comment]
فصل یک تمام شد.
