### ISSUE TITLE
ترجمه بخش دوم از فصل ۳

### ISSUE THREAD

**Issue by FatemeFouladkar** [ftg-iran/aip-persian#29]
درخواست ترجمه بخش دوم از فصل ۳ کتاب رو دارم. تاریخ اتمام ترجمه: ۲۴ تیر

**Comment by mmdbalkhi** [comment]
سلام. منظورتون از بخش دوم کدوم خطوطه؟

**Comment by FatemeFouladkar** [comment]
با توجه به جدولی که در بخش توضیحاته از خط ۶۸۳ الی ۲۱۴۲

**Comment by mmdbalkhi** [comment]
بسیار عالی میتونید شروع کنید.
